---
title: "Datenbereinigung mit OpenRefine"
subtitle: "Tabellenbereinigung für die Analyse von archäologischen Kleinfunden"
lang: de
date: 1900-01-01
date-format: "DD.MM.YYYY"
date-modified: last-modified
metadata-files:
  - _layout.yml
  - _autor_innen.yml
  - _oer_metadata.yml
# Optional
bibliography: bibliographie.bib
toc: true
toc-expand: true
toc-title: |
  {{< brand logo large >}}
toc-location: right
number-sections: true # Auf false setzen, wenn keine automatische Abschnittsnummerierung gewünscht
lightbox: true
crossref: 
  lof-title: "Liste der Abbildungen"
# Für CI-build in github
execute:
  freeze: auto
---


## Einleitung

Szenario: Ich erhalte im Forschungsprojekt eine Tabelle mit hunderten oder gar tausenden Einträgen. Leider ist die Dokumentation, wie die Datensätze entstanden sind, nicht mehr auffindbar. Dennoch ist meine Aufgabe, aus den Daten statistische Analysen zu erstellen. Ein erster Blick in die Tabelle zeigt, dass dort einiges drin steht, allerdings anscheinend keine standardisierten Eingaben gemacht wurden. Diese Tabelle muss zunächst einmal bereinigt werden, bevor sie für Analysen herangezogen werden kann.

### Lernziele {.kolophon .unnumbered .unlisted}

<!-- Idealerweise beziehen sie sich in dieser Aufzählung auf die Lernzielmatrix zum Themenbereich Forschungsdatenmanagement (FDM) für die Zielgruppen Studierende, PhDs und Data Stewards.^[Petersen, B., Engelhardt, C., Hörner, T., Jacob, J., Kvetnaya, T., Mühlichen, A., Schranzhofer, H., Schulz, S., Slowig, B., Trautwein-Bruns, U., Voigt, A., & Wiljes, C. (2023). Lernzielmatrix zum Themenbereich Forschungsdatenmanagement (FDM) für die Zielgruppen Studierende, PhDs und Data Stewards. Zenodo. [https://doi.org/10.5281/zenodo.8010617](https://doi.org/10.5281/zenodo.8010617)] -->

In diesem Skript lernen sie [@petersen2023]: 

- Kompetenz #.#

### Vorwissen {.kolophon .unnumbered .unlisted}

Für das Verständnis dieses Skripts werden vorausgesetzt:

- Voraussetzung

<!-- Versuchen sie so detailliert wie möglich die Voraussetzungen für das Verständnis des Bausteins aufzuzählen. Geben sie Hinweise, wo die Lernenden entsprechende/s Kompetenzen/Wissen erwerben können. Damit sind nicht nur Kenntnisse im Forschunsdatenmanagement gemeint sondern auch Grund-Kompetenzen aus der Data Literacy und methodisch-praktische Kompetenzen gemeint. -->

### Bezug zum Forschungsdatenlebenszyklus {.kolophon .unnumbered .unlisted}

<!-- Erläutern sie kurz, welche Rolle das Thema im Bezug auf die Phasen im Forschungsdatenzyklus spielen.

-   planen und projektieren
-   sammeln und erfassen
-   anreichern und auswerten
-   archivieren und sichern
-   teilen, veröffentlichen und auffinden
-   wiederverwenden und zitieren
-->

<!-- 

Hier ist der Raum für die Inhalte des Skripts. Nutzen sie die vielfältigen Möglichkeiten, Inhalte mit Quarto-Markdown zu gestalten. Ersetzen Sie die Überschriften "Inhaltliche Abschnitte" und "Abschnitt-Überschrift".

Viele Hinweise dazu finden sie im [Quarto-Guide](https://quarto.org/docs/guide/)

-->
## Wieso OpenRefine verwenden?

## Archäologischer Datensatz

### Tell Chuera - Kurzzusammenfassung der Grabungsgeschichte 

Tell Chuera ist ein Siedlungshügel in Nordsyrien (Jezireh-Region), der bereits zum Ende des Chalcolithikums besiedelt wurde (3100 v. Chr., 14C-datiert). Der Siedlungshügel umfasst rund 65 ha und ist durch eine innere und äußere Stadtbefestigung gekennzeichnet. In der Mitte des 3. Jahrtausends vor Christus war Tell Chuera ein Wirtschaftszentrum, das gemeinsam mit den umliegenden Orten und anderen Zentren der Region ein übergreifendes Wirtschaftssystem bildete. Anders als die anderen wissesnschaftlich erforschten wirtschaftlichen Zentren in der Jezireh wurde in Tell Chuera nie die Keilschrift adaptiert. Informationen über die wirtschaftlichen Strukturen und Prozesse in Tell Chuera ergeben sich daher - wie bei vielen unserer Kolleg:innen mit weiteren schriftlosen Forschungsschwerpunkten - lediglich aus dem archäologischen Befund.

Der Fundort Tell Chuera wurde im 20. und im frühen 21. Jahrtausend extensiv unter Anwendung verschiedenener archäologischer Methoden untersucht, darunter Luftbildaufnahmen (Flugzeug, Drache), geomagnetische Prospektionen, archäozoologische Analysen, Sedimentanalysen bis hin zur klassischen Ausgrabung.

Der hier vorliegende Datensatz stammt aus der Feder von Henrike Backhaus, die in ihrem Disserationsprojekt den "Grabungsbereich H" bearbeiten sollte.[^die Dissertation liegt aktuell wegen beruflicher anderweitiger Verpflichtungen und wirtschaftlicher Notwendigkeiten auf Eis]

Beim Grabungsbereich H handelt es sich um ein Grabungsareal im Südosten der Oberstadt (innere Stadtbefestigung). Ausgegraben wurden in diesem Bereich Gassen, Wege und Hausgrundrisse.

In insgesamt 13 Grabungskampagnen unter drei verschiedenen Direktoren wurden seit den späten 1950er bis in die frühen 2000er Jahre archäologische Daten aus Bereich H erfasst. Dabei legten die Ausgräber je einen unterschiedlichen Fokus auf dokumentierte Fundgattungen - die Technologie und Dokumentationsstandards veränderten sich (von groben Lokalisierungen der Funde bis hin zu Tachymeter-Einmessungen) - und die Nomenklatur der beschriebenen Funde und Befunde war ebenfalls nicht durchgehend standardisiert.

### Rohdaten aus Bereich H ("Häuserviertel")

Im Folgenden arbeiten wir mit einem fingierten (!) Datensatz, der sowohl die unterschiedlichen Dokumentationsweisen der drei Direktionen beinhaltet, als auch einen Teil bereits durch Henrike Backhaus bereinigter Daten.

--> Szenario: Legacy Data / Altgrabungsdaten - Excel Tabelle (ggf. noch csv) mit nicht standardisierten Eintragungen - nicht für Statistik geeignet. Abgebrochenes Projekt, alle Daten in einer Tabelle vorliegend.
--> DISCLAIMER SICHTBAR EINBAUEN, nicht dass noch jemand ernsthafte Statistiken mit den Daten machen will

::: {.column-screen-inset}
| Lfd. Nr. | Datum | Areal | Fundstelle | Beschreibung | X | Y | Z |
|------|-----|---------|------|------|-----|---------|------|
|   337  |  09.10.2003  |    Hc.III.7.West   |    261  |   Tierterrakottafragment  |  1121,98  |    368,10   |    113,48  |
|  308  |  30.09.2003 |   Hc.III.7.Ost   |   219  |   Kopf einer weibl. Terrakotte  |  9,99  |    6,60   |    112,51  |
|    323  |    01.10.2003 |     Hc.III.7.West   |     219  |   Miniaturgefäß, Profil  |  1121,39  |    362,90   |    112,33  |
:::

### Zieldaten
Ziel der Datenbereinigung ist eine statistische Analyse der Funde sowie eine räumliche Darstellung in einem geographischen Informationssystem (GIS).
Hierfür müssen die Daten zunächst gesichtet, bereinigt und standardisiert werden. Wichtig sind **unique ids** für jeden einzelnen Fund.

## Schritte der Datenbereinigung in OpenRefine

### Duplikate entfernen

### Facettierung

### Transformation
Spalte "Datum"
### Clustering
Spalte "Beschreibung" zu Materialität, Fundkategorie und Anzahl der Funde
### Ziel
Jeder Fund erhält eine ID aus Fundort (TCH) - Jahr - Fundstelle - Lfd. Nr. (ggf. Sammelfunde aufteilen und um 00X erweitern)

## Exportieren der Arbeitsschritte und der Zieldaten
### Bezug zum Forschungsdatenmanagement

## Ausblick und weiterführende Informationen

## Weiterführende Quellen und Informationen {.appendix .unnumbered}

<!-- Der Ort für weiterführende Quellen und Informationen. Wenn Sie Fußnoten oder Literaturverweise im Text eingefügt haben, werden die bibliographischen Angaben automatisch in weiteren Abschnitten generiert und in das Dokument eingefügt. -->

## Nachnutzen {.appendix .unnumbered}

Alle sind herzlich eingeladen, diesen Baustein und die zugehörige Copyleft-Lizenz zu nutzen, um ihr Wissen und Expertise in die Verbesserung und Aktualisierung einzubringen. Alle können die Inhalte erweitern oder überarbeiten, zum Beispiel um Anwendungsszenarien und Nutzungskontexte zu erweitern.

Unser Wunsch ist ein lebendiges, stetig wachsendes Dokument, das sich durch die Beiträge vieler verändert - im Einklang mit eines sich wandelnden Umfelds. Wir freuen uns im Falle einer Überarbeitung über eine kurze Notiz – das ist aber selbstverständlich keine Pflicht.

<!-- Verweise auf Website und Repository werden in _oer_metadata.yml global festgelegt. Wenn die OER nicht in einem git-Repository gehostet oder online bereitgestellt werden, können die folgenden zwei Zeilen gelöscht werden. -->

:link: [Dieser Baustein als Website]({{< meta site-url >}}) 

:link: [Quarto-Quellcode dieses Bausteins]({{< meta repo-url >}})

---

Dieses Skript nutzt das [OER-Skript-Template von NFDI4Objects](https://github.com/nfdi4objects/oer-template-skript)

## Disclaimer: Einsatz von LLM {.appendix .unnumbered}

<!-- Optionale Angaben zum Einsatz von LLM bei der Erstellung oder Überarbeitung des Skripts -->

<!-- An dieser Stelle werden von Quarto automatisch generierte Abschnitte angehängt:

Bibliographie:
Erstellt aus den in der qmd-Datei mit [@bibtex-Schlüssel] referenzierten Einträgen aus der Datei bibliographie.bib.
Im Text nicht referenzierte Einträge aus der bibliographie.bib werden nicht zitiert.
Der Zitierstil wird in der _oer_metadata.yml mit dem Schlüssel 'csl:' festgelegt. Im Verzeichnis /assets/csl/ sind gängige Zitierstile als csl-Datei vorhanden. Weitere sind hier zu finden: https://www.zotero.org/styles

Lizenz:
Angabe wird übernommen aus Schlüssel 'license:' in _oer_metadata.yml

Urheber:innen
Angabe wird übernommen aus der _oer_metadata.yml Schlüssel 'copyright:'

Zitiervorschläge
Mit BibTeX zitieren:
Automatisch von Quarto aus den Metadaten insb. aus dem Schlüssel 'citation:' in der _oer_metadata.yml generiertes bibtex-Zitat.

Bitte zitieren Sie diesen OER-Baustein als:
Angabe generiert aus:
  _autor_innen.yml
  Schlüssel 'title:' in der qmd-Datei
  Schlüssel 'issued' in der _oer_metadata.yml
  Schlüssel 'doi:' in der _oer_metadata.yml / Wenn keine doi gesetzt wird der Titel mit dem Wert aus 'site-url:' in _oer_metadata.yml verlinkt.
-->